### ISSUE TITLE
great tool

### ISSUE THREAD

**Issue by Harold2017** [davideberly/GeometricTools#10]
Thanks for your great book and tool box!

As a reader and learner, when i code by following your book examples, 
sometimes i really need some way to see the intermediate results like printing some Vec/Matrix.
But they does not support `operator<<` or provide any print-like functions.
I know it is quite usual to DIY but if you can add some facilities it would be better.

**Comment by davideberly** [comment]
I will look into doing so, but as a low-priority item. I did expect users to stream Vector/Matrix output in any format they see fit, because the format choices seem to be many. However, having a library-specific one will not prevent them from rolling their own.
