### ISSUE TITLE
No const variants for many classes

### ISSUE THREAD

**Issue by Leopard20** [davideberly/GeometricTools#12]
Lack of them makes these tools inconvenient to work with in some situations.

**Comment by davideberly** [comment]
I do not know what you mean by "no const variants for many classes." What are you trying to do that the tools are inconvenient?

**Comment by Leopard20** [comment]
It was my own mistake. That's why I closed the issue!

**Comment by davideberly** [comment]
Thank you for clarifying. I am open to suggestions on how to improve the code. If you have problems using the code, feel free to contact me. Typically I provide fast turnaround on issues.
