### ISSUE TITLE
Possible typo in IntrEllipse2Ellipse2.h resulting in wrong values

### ISSUE THREAD

**Issue by fratico** [davideberly/GeometricTools#13]
I believe the code below should read `E1.sqrExtent = ellipse1.extent * ellipse1.extent;`.
Fixing this gave me expected values when calculating intersection areas of ellipses, otherwise I sometimes end up with an intersecting area greater than any of the two ellipses referenced.

https://github.com/davideberly/GeometricTools/blob/eac03d05ea443316866c5e3662111ecd73e7094c/GTE/Mathematics/IntrEllipse2Ellipse2.h#L519

Also this is the first issue I ever opened, sorry if I missed anything.

**Comment by davideberly** [comment]
Yes, that is a bug. Thank you for taking the time to report it. I pushed the modified file. While porting GTE code to GTL, I have been revisiting all the unit tests, making them more extensive and trying to get code coverage. I will port IntrEllipse2Ellipse2, update the unit tests, and then back-port the tests to GTE.
