### ISSUE TITLE
Normalise Quaternion in RigidBody::Update?

### ISSUE THREAD

**Issue by a-jp** [davideberly/GeometricTools#16]
Hi, this is an excellent resource.  I have Geometric Tools For Computer Graphics, Robust and Error Free.., and Game Physics so I'm familiar to your book provided source code, but I really like the GitHub release.
I have been trying to use with the aid of Game Physics, the `RigidBody.h` class and the associated `void Update(Real t, Real dt)`.  I know from your books and related resources that upon time marching (`Update`) at some frequency (not often noted, recommendation?) I should ensure I normalise the Quaternion.  Here this is I guess the member variable `Quaternion<Real> mQuatOrient;`.  
I can't find anywhere explicitly where the function `Real Quaternion::Normalize(Quaternion<Real>& q)` is called in Update.

I have therefore two questions:
1) Should I call `Real Quaternion::Normalize(Quaternion<Real>& q)` after a call to `Update`? If so after normalising `Quaternion<Real> mQuatOrient;`, should I perform any subsequent operations on the other member variables of `RigidBody`?
2) I suspect this is being normalised elsewhere through other mechanics, if that is so, could you point that out to me?

Thanks,
Andy

**Comment by davideberly** [comment]
Indeed, the quaternion estimates need to be normalized before converting to rotation matrices and before calling the force and torque functions. I have added the normalization to the code. Thank you for taking the time to report this.

Regarding size of dt in the Update call, I have no guidance on this. The time step depends on your application data, and the stability analysis for a complicated physical simulation using the approaches I described in the Game Physics book is not tractable. In practice, you have to experiment with the time step in hopes of getting a stable solution to the differential equations.
