### ISSUE TITLE
Bug in IntrSegment2Triangle2.h when there is no actual intersection

### ISSUE THREAD

**Issue by AYushchenko** [davideberly/GeometricTools#18]
Possible bug if intervals do not overlap. iiQuery will return _no intersection_ and zeros in **overlap**.
**result.intersect** still be **true** and **result.numIntersections** contains wrong value
https://github.com/davideberly/GeometricTools/blob/b04395f81a994df8e1aa9be81de885b23d6889d5/GTE/Mathematics/IntrSegment2Triangle2.h#L72-L81

**Comment by AYushchenko** [comment]
Also FIQuery<Real, Line2<Real>, Triangle2<Real>> doesn't guarantee **result.parameter** to be sorted, so interval overlap checking may fail

**Comment by davideberly** [comment]
I have posted modifications to fix these bugs. The IntrRay2Trangle2 class had the same problem as IntrSegment2Triangle2. Additionally, the test-intersection query for Line2/Triangle2 was incorrect. The previous code was clearly not tested. I have added unit tests for these classes and ported the classes/tests to the in-progress GTL code. Thank you for taking the time to report the bugs.
