### ISSUE TITLE
Un-normalized directions for line or ray intersection with spheres don't work

### ISSUE THREAD

**Issue by mgamito** [davideberly/GeometricTools#20]
Hello David,

I noticed that the line or ray intersection routines with spheres don't work if the line/ray has a direction vector with magnitude other than one. This is in contrast with other geometries like boxes or cylinders where such direction vectors are allowed.
Do you think this could be improved and make the treatment of spheres more in line with other geometries?

Regards,
Manuel

**Comment by davideberly** [comment]
I believe my OrientedBox and Cylinder3 classes require unit-length vectors. In some GTE geometric queries, one might get lucky and the query happens to work. In my GTL development, I am reviewing the use of direction vectors. Removing the length constraint is useful for geometric queries using exact arithmetic, but I have many algorithms to review, so this will take some time.

**Comment by mgamito** [comment]
Oh, ok. I was under the impression that those other objects did not require normalised directions. Thanks for clearing this out for me, I will go back to my code and add protection for this situation.
