### ISSUE TITLE
Undefined behavior in IntrOrientedBox3OrientedBox3.h

### ISSUE THREAD

**Issue by aG-MathWorks** [davideberly/GeometricTools#26]
There is a bug causing undefined behavior (uninitialized Result::intersect member) due to an implicit conversion from bool to Real:

```
            // At least one pair of box axes was parallel, so the separation is
            // effectively in 2D.  The edge-edge axes do not need to be tested.
            if (existsParallelPair)
            {
                return true;
            }
```

**Comment by davideberly** [comment]
Thank you for taking the time to report the bug. Adding "explicit" to the constructor might be a quick fix to trap similar problems, but it is my opinion that the better solution is (1) have Result constructors initialize all their members and (2) ensure that the code sets any Result members should they change from the constructor defaults. I have been doing this while porting GTE to GTL and implementing a larger set of unit tests.

Another problem with IntrOrientedBox3OrientedBox3 is that the Result struct has a member 'epsilon'. Unfortunately, there is no way the caller of the operator()(...) function can set this.

I appreciate your posting a patch, but I will go ahead and fix the code on my end. The GTE-to-GTL port is nearly finished, the final set of files involving all the intersection queries. I hope to resolve the Result problems shortly during this process.

**Comment by aG-MathWorks** [comment]
Nice - I'm definitely a fan of avoiding uninitialized data members wherever possible for predictable/stable behavior across runtimes and environments (this wasn't an easy one to track down, as you can imagine). Indeed, 'explicit' was barely sufficient as a quick fix here, since there were other Result structs that take a success/fail bool as a parameter, so it would have been just as likely for someone to later add `return Result{true};`.

Even for high-performance types (like vector3), I tend to prefer an opt-in strategy for uninitialized data. GLM (for example) allows global control of default initialization with the `GLM_FORCE_CTOR_INIT` flag. I've also seen per-instance strategies (e.g. by adding additional 'no-initialize' constructors to enable client code such as `FooLib::mat3x4 m(FooLib::NoInit{})`).


Thanks for your contributions to the industry (both in print and code)!
