### ISSUE TITLE
My first try of SVD fails. Very basic test case.

### ISSUE THREAD

**Issue by ScottJohnson2718** [davideberly/GeometricTools#31]
The project that reproduces this is :
[Svd.zip](https://github.com/davideberly/GeometricTools/files/7530544/Svd.zip)

I created a simple rotation matrix of 30 degrees around X. Then I use SingularValueDecomposition to get the factoring A = U S Vt.
I assume that if I multiply the factors back together I'll get the original rotation matrix back. But that isn't true.

Original matrix A =
[ 1 0 0;
  0 0.866025 -0.5;
  0 0.5         0.866025]

Here A = U * S * transpose(V)
A = [ 1   0  0;
         0 -0.866025 -0.5;
         0 -0.5 0.866025 ]

Which is not a rotation matrix since the diagonal values 0.866 don't ​have the same sign.
I looked up "Matrix Computations" by  Golub and on page 80 it shows that for the thin SVD where m >= n, A = U * S * Vt  so that looks right. I posted this question to the Geometry3sharp where I originally encounted this, but that is C# port of this C++ code and now I've seen the same thing in the C++ code.
Any help is appreciated. 
```
int main()
{
   ​double t = 30.0 * GTE_C_DEG_TO_RAD;
   ​double rot30X[] = { 1.0, 0.0, 0.0,
                       ​0.0, cos(t), -sin(t),
                       ​0.0, sin(t), cos(t) };

   ​//SingularValueDecomposition(int numRows, int numCols, unsigned int maxIterations)
   ​gte::SingularValueDecomposition<double> svd(3, 3, 100);
   ​svd.Solve(rot30X, -1);

   ​double U[9];
   ​double S[3];
   ​double V[9];

   ​svd.GetSingularValues(S);
   ​svd.GetU(U);
   ​svd.GetV(V);

   ​std::array<double, 9> Uarray;
   ​std::memcpy(Uarray.data(), U, 9 * sizeof(double));

   ​std::array<double, 9> Varray;
   ​std::memcpy(Varray.data(), V, 9 * sizeof(double));

   ​Matrix3x3<double> Umat(Uarray);
   ​Matrix3x3<double> Vmat(Varray);
   ​Matrix3x3<double> Smat = { S[0],  0.0, 0.0,
                               ​0.0,  S[1], 0.0,
                               ​0.0,  0.0 , S[2] };

   ​Matrix3x3<double> Amat = Umat * Smat * Transpose(Vmat);

``

**Comment by davideberly** [comment]
I ran my unit tests again to see whether the norms of the error matrices E = U^T*A*V - S are nearly zero; they are. The input matrix entries are randomly generated, which generally is not sufficient to be certain, but I would have expected at least one of those cases to fail if there were some gross programming error in the SVD implementation. That said, the norm of your E matrix is 2, which is not even close to 0. The error matrix is E = Diagonal(2,0,0).

Clearly there is something wrong. I will need to debug this.

Thank you for reporting the problem.

**Comment by davideberly** [comment]
The SingularValueDecomposition.h file is now modified, a major rewrite so I could better unit test the various steps of the algorithm.
