### ISSUE TITLE
How to generate B-spline curves from discrete points

### ISSUE THREAD

**Issue by WREQI** [davideberly/GeometricTools#36]
How to generate B-spline curves from discrete points?
What's the difference from the B-spline basis function

**Comment by davideberly** [comment]
"How to generate...from discrete points?" Do you mean how do you create control points and build a B-spline curve from them? Code for this is in the file BSplineCurve.h. Or do you mean how do you fit a B-spline curve to an ordered collection of points? Code for this is in the file BSplineCurveFit.h with a mathematical description [Least-Squares Fitting of Data with B-Spline Curves](https://www.geometrictools.com/Documentation/BSplineCurveLeastSquaresFit.pdf). A sample application for the fitting is in the folder GeometricTools/Samples/Mathematics/BSplineCurveFitter.

A B-spline basis function is a scalar-valued function of a scalar input. B-spline curves (and NURBS curves) are built as a combination of control points where the coefficients are B-spline basis functions. This is a large topic that I cannot describe in this forum, so you might want to research the topic online.
