### ISSUE TITLE
Is code for detecting duplicates in class Delaunay2<T>::ProcessedVertex not working right?

### ISSUE THREAD

**Issue by maquemo** [davideberly/GeometricTools#41]
According to code, apart of the X and Y coordinates also the location (index inside the vector of available vertices) is hashed and used in comparation, so I think it will never detect the duplication.

**Comment by davideberly** [comment]
I will look into this shortly to verify there is a problem, and if so, fix it. Thank you for letting me know.

**Comment by davideberly** [comment]
I tried some examples with duplicate vertices. The duplicates were correctly found. Will you provide me with a dataset for which at least one duplicate vertex is not found? Thank you.
