### ISSUE TITLE
unexcpected behaviour in Arc2.Contains(2Dpoint) 

### ISSUE THREAD

**Issue by owai1980** [davideberly/GeometricTools#46]
Hello,

I think this function tests if a 2D point is on the Arc ? on the "line" of the arc, right ? not inside the surface of the "pie" ?

If i'm right, then i don't understand why the function returns "true" when i test if the Arc[ACB] Contains the point "D" :

Thank your for your advice,

Johan

![image](https://user-images.githubusercontent.com/28708929/199532915-85035488-c40b-4692-8311-4f141e2c9b1d.png)

**Comment by davideberly** [comment]
The Arc2.Contains function requires P to be on the circle of the arc or nearly on the circle within floating-point tolerance. I added a fuzzy containment that determines whether P is on (or nearly on) the circle. If so, the test of the non-fuzzy comparison is performed. If not, the function returns false (P not on arc because it is not on circle). Based on your post, I believe you want the new Contains function.

```
    Arc2<double> arc{};
    arc.center = { 800.0, -200.0 };
    arc.end[0] = { 1591.8964578782, 30.0 };
    arc.end[1] = { 8.1035421218, 30.0 };
    arc.radius = Length(arc.end[0] - arc.center);
    // = Length(arc.end[1] - arc.center)
    // = 824.62112512355623

    // Your 'point' is not on the circle containing the arc. The comment
    // in Arc2<T>::Contains is
    //
    // Assert: |P-C| = R where P is the input point, C is the circle
    // center and R is the circle radius.  For P to be on the arc from
    // A to B, it must be on the side of the plane containing A with
    // normal N = Perp(B-A) where Perp(u,v) = (v,-u).
    Vector2<double> point{ 1560.6068185945, 30.0 };
    bool contains = arc.Contains(point);
    // contains = true
    // This result is invalid because 'length' is 794.62112512344311
    // which is not the radius of the circle.
    double length = Length(point - arc.center);
    (void)length;

    // Project the point onto the arc.
    Vector2<double> diff = point - arc.center;
    Normalize(diff);
    Vector2<double> scaledPoint = arc.center + arc.radius * diff;
    contains = arc.Contains(scaledPoint);

    // New code for 'fuzzy' containment.
    double epsilon = 1e-08;
    contains = arc.Contains(point, epsilon);
    // contains = false
    // The point is farther away from the circle than allowed.
    contains = arc.Contains(scaledPoint, epsilon);
    // The point is with tolerance of the circle and is deemed
    // to be on the arc.

**Comment by owai1980** [comment]
wow!
thank you for this fast and complete answer!! :-)
and... the updated repository :-)

I just tested the new function with the epsilon, it works prefectly and i agree that this "tolerance" is needed with floating point values.

thank you... once again!

**Comment by davideberly** [comment]
You are welcome.
