### ISSUE TITLE
FIQuery<T, Line2<T>, Line2<T>> result wrong.

### ISSUE THREAD

**Issue by sonygod** [davideberly/GeometricTools#49]
the result point should be [2.0,2.0] but got [-2.0,-2.0]

```cpp
  Line2<float_t> line2_3({0.0, 0.0}, {0.5, 0.5});

    Line2<float_t> line2_4({2.0, 0.0}, {2.0, 1.0});

   IntrPointLine2AndLine2<float_t> intrLine2AndLine2;

    auto result6 = intrLine2AndLine2(line2_3, line2_4);
    
   Vector2<float_t> respect = {2.0f, 2.0f};
    assert(result6.point == respect);
```

<img width="514" alt="image" src="https://user-images.githubusercontent.com/748320/205431010-1bc16f1b-f45a-44a1-828f-2937e4add317.png">

**Comment by sonygod** [comment]
Tests whether parallel lines intersect  fail.


```
 Line2<float_t> line2_5({0.0, 0.0}, {1.0, 0.0});

    Line2<float_t> line2_6({0.0, 1.0}, {1.0, 1.0});


    IntrPointLine2AndLine2<float_t> intrLine2AndLine2_2;

    auto result7 = intrLine2AndLine2_2(line2_5, line2_6);

    assert(result7.intersect == false);
```

**Comment by owai1980** [comment]
Hello, I'm not sure, but I think the line2 objects are not defined by 2
points, but 1 point + direction unit vector. (distance between the two
points must be "1")

So... If your lines are not well defined, ofc the result is bad...

(this is just my opinion)

**Comment by sonygod** [comment]
thanks, yes, line 2 is defined by 1 point and direction instead of two points.
