### ISSUE TITLE
IntgRomberg.h cannot be found

### ISSUE THREAD

**Issue by WangYan-CN** [davideberly/GeometricTools#52]
I can't find GTL/Mathematics/Integration/IntgRomberg.h in master branch. But this file is used by ParametricCurve.h.

**Comment by WangYan-CN** [comment]
Okay, thank you very much.This open source project is like a bridge, connecting abstract mathematics and beautiful geometry.

**Comment by owai1980** [comment]
i really agree with you :-) wonderful work!!
