### ISSUE TITLE
Bug in box and cylinder intersection judgement

### ISSUE THREAD

**Issue by Gatevin** [davideberly/GeometricTools#58]
Hello, recently I use the newest released package [GTE-version-6.5](https://github.com/davideberly/GeometricTools/releases/tag/GTE-version-6.5) to judge intersection of box and cylinder, but found something seems like a bug.

## Problem
I downloaded the package and changed the cylinder property to run the box and cylinder intersection sample, the test result is wrong.

## The test case
After change the function `void IntersectBoxCylinderWindow3::CreateScene()` in 
`GTE/Samples/Intersection/IntersectBoxCylinder/IntersectBoxCylinderWindow3.cpp`  to
```csharp
void IntersectBoxCylinderWindow3::CreateScene()
{
    VertexFormat vformat;
    vformat.Bind(VASemantic::POSITION, DF_R32G32B32_FLOAT, 0);
    MeshFactory mf;
    mf.SetVertexFormat(vformat);

    // mCylinder.axis.origin = { 3.0f, 2.0f, 3.0f };
    // mCylinder.axis.direction = { 0.0f, 0.0f, 1.0f };
    // mCylinder.radius = 1.0f;
    // mCylinder.height = 8.0f;
    // I changed the cylinder property only
    mCylinder.axis.origin = { 6.0f, 0.0f, 0.0f };
    mCylinder.axis.direction = { -0.017459368f, -0.9998476f, 0.0f };
    mCylinder.radius = 0.5f;
    mCylinder.height = 2.0f;

    mCylinderMesh = mf.CreateCylinderClosed(16, 16, mCylinder.radius, mCylinder.height);
    mCylinderMesh->localTransform.SetTranslation(mCylinder.axis.origin);
    auto effect = std::make_shared<ConstantColorEffect>(mProgramFactory,
            Vector4<float>{ 0.0f, 0.5f, 0.0f, 0.5f });
    mCylinderMesh->SetEffect(effect);
    mPVWMatrices.Subscribe(mCylinderMesh->worldTransform, effect->GetPVWMatrixConstant());

    mRedEffect = std::make_shared<ConstantColorEffect>(mProgramFactory,
        Vector4<float>{ 0.5f, 0.0f, 0.0f, 0.5f });

    mBlueEffect = std::make_shared<ConstantColorEffect>(mProgramFactory,
        Vector4<float>{ 0.0f, 0.0f, 0.5f, 0.5f });

    mBox.center = { 0.0f, 0.0f, 0.0f };
    mBox.axis[0] = { 1.0f, 0.0f, 0.0f };
    mBox.axis[1] = { 0.0f, 1.0f, 0.0f };
    mBox.axis[2] = { 0.0f, 0.0f, 1.0f };
    mBox.extent = { 1.0f, 2.0f, 3.0f };

    mBoxMesh = mf.CreateBox(mBox.extent[0], mBox.extent[1], mBox.extent[2]);
    mBoxMesh->SetEffect(mBlueEffect);
    mPVWMatrices.Subscribe(mBoxMesh->worldTransform, mBlueEffect->GetPVWMatrixConstant());

    mTrackBall.Attach(mCylinderMesh);
    mTrackBall.Attach(mBoxMesh);
    mTrackBall.Update();
}
```

## Result expected
The intersection test function gives `intersected`, but obviously they are not intersected.

## Attachment
Here is the snapshot.
<img width="1050" alt="bug" src="https://user-images.githubusercontent.com/7897367/226553949-97900c0f-0812-477d-bab7-fa739c64fd92.PNG">

**Comment by davideberly** [comment]
I apologize for taking so long. Other bug investigations and fixes were in front of this one in my technical support queue.

In fact there was a bug in IntrCanonicalBox3Cylinder3.h. My unit tests found this in my local GTL development, and I fixed it there, but I failed to back-port it to GTE. I have posted the fix.
