### ISSUE TITLE
Testing algorithms implementation

### ISSUE THREAD

**Issue by rradev** [davideberly/GeometricTools#64]
How are all algorithms tested for correctness?
I do not see any tests.

**Comment by davideberly** [comment]
I have not posted my GTE test environment that includes unit tests, end-to-end tests, several manual tests, and instantiation of template classes and functions to ensure that all compile.

**Comment by rradev** [comment]
I understand.
It make sense, for such core math library, when the user builds it on a specific hardware/compiler/options environment, to run all the unit test and ensure no test are failing. At leas this is what I have seen on most math libraries.
Thanks, for providing this useful set of tools.

**Comment by davideberly** [comment]
I plan on posting the unit tests for GTL. Thank you for the feedback.
