### ISSUE TITLE
question 3D mesh CSG (boolean operations)

### ISSUE THREAD

**Issue by owai1980** [davideberly/GeometricTools#67]
Hello,

Does your library allow to do simple boolean operations (intersection, substraction, union) on two 3D closed mesh of triangles ?

thank you... again!

**Comment by davideberly** [comment]
Currently, I do not have a computational solid geometry (CSG) component in GTE. That is a nontrivial project. It is on my very-long-term TODO list. The closest I have to this is SplitMeshByPlane.h, which splits a mesh by a plane but it does not attempt to "close" the mesh halves. See [Clipping a Mesh Against a Plane](https://www.geometrictools.com/Documentation/ClipMesh.pdf). A sample application is GeometricTools/GTE/Samples/Geometrics/SplitMeshByPlane which shows partitioning of a torus mesh by a plane.

CSG is difficult to make robust when using floating-point arithmetic, even if two solids are convex polyhedra. You have to compute using rational arithmetic. The ideas for Boolean operations are shown in [Polysolids and Boolean Operations](https://www.geometrictools.com/Documentation/Polysolids.pdf).

**Comment by owai1980** [comment]
Thank you for your answer!

And thank you for this great library! 👍



Le lun. 14 août 2023 à 00:00, David Eberly ***@***.***> a
écrit :
