### ISSUE TITLE
Question about MovingAlongCurveSpecifiedSpeed integral equation 5 on page 3

### ISSUE THREAD

**Issue by atship** [davideberly/GeometricTools#68]
Hi,
I read the paper https://www.geometrictools.com/Documentation/MovingAlongCurveSpecifiedSpeed.pdf
and I get confused at the integral equation $g(t) = \int_{tmin}^{t}|\frac{dY(\\tau)}{dt}|d\\tau$
I asked the integral equation on quora and they said this equation is wrong or not make sense etc.
my question is why function Y is expected to $\\tau$ but derivative with dt? 
Would you point me to the right way? Thank you in advance.

**Comment by davideberly** [comment]
The variable t appears in the upper limit of integration. If I were to use the same t in the integrand, that t is a name conflict with the upper limit. Abstractly, if you write $g(t) = \int_{tmin}^{t} f(t) dt$, t acts as the variable of integration and the upper limit of integration. It is typical that a different variable name be used for the integrand: $g(t) = \int_{tmin}^{t} f(\tau) d\tau$.

**Comment by atship** [comment]
Thank you for your reply.
If I am not misunderstanding, the origin integration equation would rewrite as $\int_{tmin}^{t}|\frac{dY(x)}{dx}|dx$ right?
I was confused by the $dt$ in the integrand but $d\\tau$ in the integration variable

**Comment by davideberly** [comment]
Your rewrite is correct. I am revising the document to avoid the confusion. The derivative of Y has 2 names, dY/dt and Y’. The fact that t occurs in the first name is the issue for you. The rewrite uses the second name. I am also revising the pseudocode because, in practice, Newton’s iterates can occur in a cycle. When it does, the maximum number of iterations will occur, but the first revisited iterate will suffice.

**Comment by atship** [comment]
My confusion is resolved.
Thank you, sir.

**Comment by davideberly** [comment]
I posted a revised document [Moving Along a Curve with Specified Speed](https://www.geometrictools.com/Documentation/MovingAlongCurveSpecifiedSpeed.pdf). Source code that illustrates is in a new header file ReparameterizeByArclength.h.
