### ISSUE TITLE
Installation and Release Notes page not loading

### ISSUE THREAD

**Issue by DM-christiangomez** [davideberly/GeometricTools#69]
When I navigate to the [Installation and Release Notes](https://github.com/davideberly/GeometricTools/blob/master/GTE/Gte6p5InstallationRelease.pdf) page, it says the page does not exist in master:

![image](https://github.com/davideberly/GeometricTools/assets/30630264/b3e8b965-ed14-41fa-a78f-df6d7a6d5ba1)

**Comment by davideberly** [comment]
I failed to update that link to current version (for several versions now). I fixed the link (current version is 6.8). Thank you for reporting this.
