### ISSUE TITLE
Typo in Hyperplane::operator< - wrong comparison

### ISSUE THREAD

**Issue by andreyyfrolov** [davideberly/GeometricTools#74]
There is a typo in Hyperplane class, that could lead to incorrect order of sorted planes

`bool operator< (Hyperplane const& hyperplane) const
        {
            if (normal < hyperplane.normal)
            {
                return true;
            }

            if (origin > hyperplane.origin)       // original
            // if (normal > hyperplane.normal)   // correct
            {
                return false;
            }

            if (origin < hyperplane.origin)
            {
                return true;
            }

            if (origin > hyperplane.origin)
            {
                return false;
            }

            return constant < hyperplane.constant;
        }`

**Comment by davideberly** [comment]
Yes, that is a bug. I have fixed it and pushed the modified Hyperplane.h file. Thank you for taking the time to report this.
