### ISSUE TITLE
Why did the LInfinityNorm function M [0] of Matrix not take an absolute value

### ISSUE THREAD

**Issue by WuyangPeng** [davideberly/GeometricTools#85]
template <int32_t NumRows, int32_t NumCols, typename Real>
Real LInfinityNorm(Matrix<NumRows, NumCols, Real> const& M)
{
    Real maxAbsElement = M[0];
    for (int32_t i = 1; i < NumRows * NumCols; ++i)
    {
        Real absElement = std::fabs(M[i]);
        if (absElement > maxAbsElement)
        {
            maxAbsElement = absElement;
        }
    }
    return maxAbsElement;
}

**Comment by davideberly** [comment]
You have a polite way of saying "There is a bug in your code." Thank you for reporting this. I have pushed the fix to the repository. This is GTE code. I looked at the GTL code and verified that code is correct.

**Comment by davideberly** [comment]
Closing the issue because the bug is fixed.
