### ISSUE TITLE
Largest Fixed-Aspect, Axis-Aligned Rectangle?

### ISSUE THREAD

**Issue by zickler** [davideberly/GeometricTools#87]
Is there an implementation of the _Largest Fixed-Aspect, Axis-Aligned Rectangle_ algorithm described in your document https://www.geometrictools.com/Documentation/MaximumAreaAspectRectangle.pdf?

**Comment by davideberly** [comment]
I implemented it and tested it compared to what Mathematica computes with NMaximize (with constraints). The file is GeometricTools/Mathematics/InscribedFixedAspectRectInQuad.h

**Comment by davideberly** [comment]
I will assume that this file works for you. If not, feel free to post again for this issue! (BTW, the same idea applies to fixed-aspect axis-aligned rectangle inscribed in an arbitrary convex polygon.)
