### ISSUE TITLE
bug in Segment2Circle2 intersection

### ISSUE THREAD

**Issue by owai1980** [davideberly/GeometricTools#95]
Hello,

I found a problem when trying to intersect a segment2 with a circle2 (but i guess the problem is the same for dimensions > 2). Same problem with "double" or "bsrational" precision .

First, I assume that a "Circle 2" is not "filled" ... i mean, when we talk about hyperspheres (circle2), we talk about the "contour", right?

here are my objects... the gray points are the 2 intersections found. I wanted only 1 intersection...

![image](https://github.com/user-attachments/assets/116a056c-de2d-4986-afce-32f5fa2d7106)

circle2 = center (1150,1000) radius (250)
segment2 = (1250, 1050) (250,900)

when i read the code in "IntrSegment2Circle2.h", i see that you do a "Line - Circle" intersection, then an "interval" intersection to keep the common part. But there's no test to check if the point is actually on the circle, you accept it if it's inside too.

Maybe because i think a circle2 is empty, and you think it's "filled" ?

thank you!

johan

**Comment by davideberly** [comment]
I intended the circle to be "hollow", not "solid." I will investigate.

**Comment by owai1980** [comment]
ok!! thank you :-)

i'm happy we agree about what is a "Circle" !

**Comment by owai1980** [comment]
Thank you for the explanation!

And sorry for not reading this line about the disk...

Yeah, now it's quite easy to filter out the intersection that I don't
want...

Thank you again!

Johan

Le jeu. 24 oct. 2024 à 19:10, David Eberly ***@***.***> a
écrit :

**Comment by davideberly** [comment]
Based on poster's last response, the issue is closed.
